<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Request extends Model
{

    protected $table = 'request';
    protected $fillable = [
        'uid',
        'empresa',
        'rfc',
        'curp',
        'domicilio_fiscal',
        'colonia',
        'ciudad',
        'municipio',
        'estado',
        'cp',
        'telefono_1',
        'telefono_2',
        'celular',
        'correo_electronico',
        'apoderado_legal',
        'nombre_del_contacto',
        'consumo_anual_de_fertilizante',
        'referencia_1_banco',
        'referencia_1_sucursal',
        'referencia_1_ejecutivo_de_cuenta',
        'referencia_1_telefono_1',
        'referencia_1_telefono_2',
        'referencia_1_celular',
        'referencia_1_ciudad',
        'referencia_1_municipio',
        'referencia_1_estado',
        'referencia_2_banco',
        'referencia_2_sucursal',
        'referencia_2_ejecutivo_de_cuenta',
        'referencia_2_telefono_1',
        'referencia_2_telefono_2',
        'referencia_2_celular',
        'referencia_2_ciudad',
        'referencia_2_municipio',
        'referencia_2_estado',
        'empresa_1_rfc',
        'empresa_1_domicilio_fiscal',
        'empresa_1_cp',
        'empresa_1_ciudad',
        'empresa_1_municipio',
        'empresa_1_telefono_1',
        'empresa_1_telefono_2',
        'empresa_1_celular',
        'empresa_1_correo_electronico',
        'empresa_1_nombre_del_contacto',
        'empresa_2_rfc',
        'empresa_2_domicilio_fiscal',
        'empresa_2_cp',
        'empresa_2_ciudad',
        'empresa_2_municipio',
        'empresa_2_telefono_1',
        'empresa_2_telefono_2',
        'empresa_2_celular',
        'empresa_2_correo_electronico',
        'empresa_2_nombre_del_contacto',
        'acta_constitutiva',
        'constancia_situacion_fiscal',
        'poder_notarial',
        'identificacion_oficial',
        'comprobante_curp',
        'formato_32_d',
    ];
}
